language: python
python:
  - "3.6"

install:
  - pip install distro
  - pip install kodi-addon-checker
  - pip install pylint
  - pip install jsonschema

before_script:
  - cd $HOME

script:
  - kodi-addon-checker $TRAVIS_BUILD_DIR --branch=gotham
  - pylint $TRAVIS_BUILD_DIR/resources/lib/
  - jsonschema -i $TRAVIS_BUILD_DIR/resources/versions.txt $TRAVIS_BUILD_DIR/resources/versions.schema.txt
