name: Add-on Validations

on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main ]

jobs:

  addon-validations:
    if: github.repository == 'XBMC-Addons/service.xbmc.versioncheck'

    runs-on: ubuntu-latest

    name: Add-on Validations

    steps:
      - name: Set up Python v3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Checkout Add-on
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}

      - name: Checkout kodi-addon-checker
        uses: actions/checkout@v2
        with:
          repository: xbmc/addon-check
          path: addon-check

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install jsonschema
          python -m pip install pylint
          python -m pip install addon-check/

      - name: Staging
        run: |
          cp -t ${HOME} .pylintrc
        working-directory: ${{ github.event.repository.name }}

      - name: Kodi Add-on Checker
        id: kodi-addon-checker
        run: |
          kodi-addon-checker ${{ github.event.repository.name }} --branch=leia

      - name: Pylint
        id: pylint
        run: |
          pylint --ignore=distro resources/lib/
        working-directory: ${{ github.event.repository.name }}

      - name: JSONSchema
        id: jsonschema
        run: |
          jsonschema -i resources/versions.txt resources/versions.schema.txt
        working-directory: ${{ github.event.repository.name }}
